[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 run.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
FLASK_ENV = "production"
